//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsClient.SingleService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SingleService.ISingleService")]
    public interface ISingleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingleService/GetEvenNumbers", ReplyAction="http://tempuri.org/ISingleService/GetEvenNumbersResponse")]
        int[] GetEvenNumbers(int n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingleService/GetEvenNumbers", ReplyAction="http://tempuri.org/ISingleService/GetEvenNumbersResponse")]
        System.Threading.Tasks.Task<int[]> GetEvenNumbersAsync(int n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingleService/GetOddNumbers", ReplyAction="http://tempuri.org/ISingleService/GetOddNumbersResponse")]
        int[] GetOddNumbers(int n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingleService/GetOddNumbers", ReplyAction="http://tempuri.org/ISingleService/GetOddNumbersResponse")]
        System.Threading.Tasks.Task<int[]> GetOddNumbersAsync(int n);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISingleServiceChannel : WindowsFormsClient.SingleService.ISingleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SingleServiceClient : System.ServiceModel.ClientBase<WindowsFormsClient.SingleService.ISingleService>, WindowsFormsClient.SingleService.ISingleService {
        
        public SingleServiceClient() {
        }
        
        public SingleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SingleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SingleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SingleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int[] GetEvenNumbers(int n) {
            return base.Channel.GetEvenNumbers(n);
        }
        
        public System.Threading.Tasks.Task<int[]> GetEvenNumbersAsync(int n) {
            return base.Channel.GetEvenNumbersAsync(n);
        }
        
        public int[] GetOddNumbers(int n) {
            return base.Channel.GetOddNumbers(n);
        }
        
        public System.Threading.Tasks.Task<int[]> GetOddNumbersAsync(int n) {
            return base.Channel.GetOddNumbersAsync(n);
        }
    }
}
